# git-reset
# Autogenerated from man page /usr/share/man/man1/git-reset.1.gz
complete -c git-reset -s q -l quiet -l no-quiet --description 'Be quiet, only report errors.  The default behavior is set by the reset.'
complete -c git-reset -l patch --description 'mode.  git reset [<mode>] [<commit>].'
complete -c git-reset -l mixed --description '<mode> must be one of the following:.'
complete -c git-reset -l soft --description '.'
complete -c git-reset -s N --description 'is specified, removed paths are marked as intent-to-add (see git-add(1)).'
complete -c git-reset -l hard --description '.'
complete -c git-reset -l merge --description '.'
complete -c git-reset -l keep --description '.'
complete -c git-reset -s C --description 'option instead.'
complete -c git-reset -l amend --description 'option to git-commit(1).'
complete -c git-reset -s c --description 'option specifies to pre-populate the commit message from the original message…'
complete -c git-reset -l -------------------------------------------------- --description ' A       B     C    D     --soft   A       B     D                           …'

