# git-multi-pack-index
# Autogenerated from man page /usr/share/man/man1/git-multi-pack-index.1.gz
complete -c git-multi-pack-index -l object-dir --description 'Use given directory for the location of Git objects.'

