# mariadb_config
# Autogenerated from man page /usr/share/man/man1/mariadb_config.1.gz
complete -c mariadb_config -l cflags --description '.'
complete -c mariadb_config -l include --description 'for more portable options that contain only include paths.  oc o 2. 3.'
complete -c mariadb_config -l libmysqld-libs --description '.'
complete -c mariadb_config -l embedded --description '.'
complete -c mariadb_config -l libs --description '.'
complete -c mariadb_config -l libs_r --description '.'
complete -c mariadb_config -l plugindir --description '.'
complete -c mariadb_config -l port --description '.'
complete -c mariadb_config -l socket --description '.'
complete -c mariadb_config -l variable --description '.'
complete -c mariadb_config -l version --description '.'

